version: 1
names:
  family: Apple Color Emoji
bitmap:
  format: cbdt_cblc
  strikes:
    - 20
    - 26
    - 32
    - 40
    - 48
    - 52
    - 64
    - 96
  generated_strikes:
    source: 160
    sizes:
      - 56
      - 72
      - 80
      - 88
  png:
    compress: true
    strikes:
      - 56
      - 72
      - 80
      - 88
    max_colors: 128
    prefer_pngquant: true
  metrics:
    y_bearing: line_center
    line_source: os2_win
tables:
  drop:
    source_tables: true
    outlines: false
    dsig: true
  cmap:
    bmp: true
    ucs4: true
    entries:
      - codepoint: 13
        glyph: .controlCR
  metrics:
    hhea:
      ascent: 1491
      descent: -431
      line_gap: 269
    os2:
      version: 4
      x_avg_char_width: 2785
      us_weight_class: 400
      us_width_class: 5
      fs_type: 8
      y_subscript_x_size: 1434
      y_subscript_y_size: 1331
      y_subscript_x_offset: 0
      y_subscript_y_offset: 283
      y_superscript_x_size: 1434
      y_superscript_y_size: 1331
      y_superscript_x_offset: 0
      y_superscript_y_offset: 977
      y_strikeout_size: 102
      y_strikeout_position: 530
      s_family_class: 2053
      s_typo_ascender: 1491
      s_typo_descender: -431
      s_typo_line_gap: 269
      us_win_ascent: 2210
      us_win_descent: 514
      fs_selection: 64
      us_first_char_index: 13
      us_last_char_index: 65535
      s_cap_height: 1434
      sx_height: 1024
      us_max_context: 7
      unicode_range_1: 1
      unicode_range_2: 33554432
      unicode_range_3: 134217728
      unicode_range_4: 0
      code_page_range_1: 1
      code_page_range_2: 0
      panose:
        family_type: 2
        serif_style: 11
        weight: 5
        proportion: 2
        contrast: 4
        stroke_variation: 2
        arm_style: 4
        letter_form: 2
        midline: 2
        x_height: 3
  head:
    units_per_em: 2048
    mac_style: 0
  post:
    format: 3
shaping:
  gsub:
    enabled: true
    sequence_files:
      - ../sequences/emoji-sequences.txt
      - ../sequences/emoji-zwj-sequences.txt
      - ../sequences/emoji-test.txt
      - ../sequences/emoji-variation-sequences.txt
    project_sequence_files:
      - ../sequences/project-sequences.txt
    replace_morx: false
